version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=makerops
      - POSTGRES_PASSWORD=makerops
      - POSTGRES_DB=makerops
